name: CI Build

on:
  workflow_dispatch:
    branches: [main]
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   packages: read

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ekarpovs'
      # - run: echo "@ekarpovs:registry=https://npm.pkg.github.com" > ~/.npmrc
      # - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.REGISTRY_TOKEN }}" >> ~/.npmrc
      # - run: more ~/.npmrc
      - name: Install dependencies
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      - name: Run build
      - run: npm run build --if-present
      - name: Run tests
      - run: npm test
