name: CI build

on:
  workflow_dispatch:
    branches: [main]
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18x'

      - name: Authenticate with private NPM package
      - run: echo "@ekarpovs:registry=https://npm.pkg.github.com" > .npmrc
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_REGISTRY_TOKEN }}" >> .npmrc

      - name: Install dependencies
      - run: npm ci

      - name: Run build
      - run: npm run build --if-present

      - name: Run tests
      - run: npm test
