name: CI build

on:
  workflow_dispatch:
    branches: [main]
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: echo "@ekarpovs:registry=https://npm.pkg.github.com" > .npmrc
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.REGISTRY_TOKEN }}" >> .npmrc
      - run: npm ci
        # with:
        #   registry-url: 'https://npm.pkg.github.com'
        #   # Defaults to the user or organization that owns the workflow file
        #   scope: '@ekarpovs'
      - run: npm run build --if-present
      - run: npm test
      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
