name: CI Deploy to Render

on:
  workflow_dispatch:
    branches: [main]
  #   workflows: ["CI Build"]
  #   types:
  #     - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
